export const TIMELINE_CONSTANTS = {
  TRACK_SPACING: 6,
  TRACK_PADDING_TOP: 6,
  PIXELS_PER_SECOND: 50,
  MICROSECONDS_PER_SECOND: 1_000_000,
  RULER_HEIGHT: 24,
  DEFAULT_ZOOM: 1,
  DEFAULT_FPS: 30,
} as const;
